### ISSUE TITLE
How to install in cabal sandbox?

### ISSUE THREAD

**Issue by gitfoxi** [christiaanb/clash2#34]
I couldn't install with the recommended `cabal install clash-gcc` because of too many clashes with other installed packages (is that where the name "clash" comes from?). I got it to build in a sandbox but now

```
$ .cabal-sandbox/bin/clash --interactive
CLaSHi, version 0.3.3 (using clash-lib, version 0.3.2):
http://christiaanb.github.io/clash2/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.

Top level:
    Failed to load interface for ‘CLaSH.Prelude’
    Use -v to see a list of the files searched for.
```

**Comment by Ericson2314** [comment]
I've used (and developed) CLaSH from a sandbox all 2015 without issue---keeping each package in a subdirectory as we do now makes this more convenient. I guess this can be closed then?
